### ISSUE TITLE
关于挖掘榜的实现

### ISSUE THREAD

**Issue by Sciroccogti** [TISUnion/StatsHelper#1]
您好，我注意到在TIS中有“挖掘榜”，但是 *Minecraft* 中并不能直接实现，而代码中似乎也没有反映。

请问你们是如何实现的呢？

感谢！

**Comment by Sciroccogti** [comment]
自问自答：是按钻石镐使用次数计算的。

**Comment by source-dream** [comment]
可以通过遍历服务器的挖掘方块的数据实现

我Fork了本仓库 实现挖掘榜的功能外还实现了轮播功能 等开发完善之后再尝试提PR
