### ISSUE TITLE
Suggestion: Using a config json to recognize bots

### ISSUE THREAD

**Issue by EasonSYC** [TISUnion/StatsHelper#9]
Sometimes, bots in servers may not have the 'bot' in the name string (such as xxx_loader, Camera, or some other bots name for fun). Reading the real players' name from a config json may help stopping these bots from appearing on the scoreboard.

**Comment by EasonSYC** [comment]
related to PR #8

**Comment by Fallen-Breath** [comment]
PR #8 is merged
